### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sahadev123** [fitrialif/Licence-Plate-Recognition-Keras#1]
Attempting to use uninitialized value dense2/kernel
	 [[Node: dense2/kernel/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](dense2/kernel)]]
	 [[Node: reshape/Shape/_3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_34_reshape/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by sahadev123** [comment]
why is this error coming during running the script ?

**Comment by fitrialif** [comment]
What backend do you used ?

**Comment by sahadev123** [comment]
I am using tensorflow .

**Comment by fitrialif** [comment]
What python version do used
Do you used on windows or ubuntu

**Comment by sahadev123** [comment]
I am using python version 3.6.5 and ubutu 18.04

**Comment by fitrialif** [comment]
I used python 2.7 and ubuntu 14.04
Tensorflow 1.8 and keras 2.2.2
